/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.cicd.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.cicd.ui.internal.CicdActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CICDExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CicdActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CicdActivator activator = CicdActivator.getInstance();
		return activator != null ? activator.getInjector(CicdActivator.ORG_XTEXT_EXAMPLE_CICD_CICD) : null;
	}

}
