/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.gha.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.gha.GHARuntimeModule;
import org.xtext.example.gha.GHAStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GHAIdeSetup extends GHAStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GHARuntimeModule(), new GHAIdeModule()));
	}
	
}
