/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.jenkins.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJenkinsScopeProvider extends DelegatingScopeProvider {
}
