/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.gha.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGHAScopeProvider extends DelegatingScopeProvider {
}
