/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.circleci.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.xtext.example.circleci.parser.antlr.internal.InternalCircleciParser;

public class CircleciTokenSource extends AbstractIndentationTokenSource {

	public CircleciTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalCircleciParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalCircleciParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalCircleciParser.RULE_END;
	}

}
