/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.gha.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GHAUiModule extends AbstractGHAUiModule {

	public GHAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
