<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devOps" nsURI="http://www.example.org/devOps" nsPrefix="devOps">
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tool_framework_job" upperBound="-1"
        eType="#//Tool_Framework" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifthenelse" upperBound="-1"
        eType="#//IfThenElse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Allow_faillure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permission" upperBound="-1"
        eType="#//Permission" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" upperBound="-1" eType="#//When"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" upperBound="-1" eType="#//Job"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline_tool_framework"
        upperBound="-1" eType="#//Tool_Framework" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline_environment" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permission" upperBound="-1"
        eType="#//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parallel" upperBound="-1"
        eType="#//Parallel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool_Framework">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tool" eType="#//Tool_Framework"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" upperBound="-1" eType="#//Job"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" upperBound="-1" eType="#//Command"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" upperBound="-1" eType="#//Command"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifelse" upperBound="-1"
        eType="#//IfThenElse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseif" upperBound="-1"
        eType="#//IfThenElse" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="When">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Trigger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Timer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
