/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.gha.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.gha.ui.internal.GhaActivator;

public class GHAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GhaActivator.getInstance().getInjector("org.xtext.example.gha.GHA");
	}

}
