/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.jenkins.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.jenkins.services.JenkinsGrammarAccess;

@SuppressWarnings("all")
public class JenkinsSyntacticSequencer extends AbstractSyntacticSequencer {

	protected JenkinsGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_2_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_3_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_4_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_5_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_6_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_7_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_8_1_q;
	protected AbstractElementAlias match_Pipeline_NEWLINETerminalRuleCall_9_1_q;
	protected AbstractElementAlias match_PreserveStashes___BEGINTerminalRuleCall_2_0_ENDTerminalRuleCall_2_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (JenkinsGrammarAccess) access;
		match_Pipeline_NEWLINETerminalRuleCall_2_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_2_1());
		match_Pipeline_NEWLINETerminalRuleCall_3_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_3_1());
		match_Pipeline_NEWLINETerminalRuleCall_4_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_4_1());
		match_Pipeline_NEWLINETerminalRuleCall_5_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_5_1());
		match_Pipeline_NEWLINETerminalRuleCall_6_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_6_1());
		match_Pipeline_NEWLINETerminalRuleCall_7_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_7_1());
		match_Pipeline_NEWLINETerminalRuleCall_8_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_8_1());
		match_Pipeline_NEWLINETerminalRuleCall_9_1_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getNEWLINETerminalRuleCall_9_1());
		match_PreserveStashes___BEGINTerminalRuleCall_2_0_ENDTerminalRuleCall_2_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPreserveStashesAccess().getBEGINTerminalRuleCall_2_0()), new TokenAlias(false, false, grammarAccess.getPreserveStashesAccess().getENDTerminalRuleCall_2_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getBEGINRule())
			return getBEGINToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getENDRule())
			return getENDToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getNEWLINERule())
			return getNEWLINEToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Synthetic terminal rule. The concrete syntax is to be specified by clients.
	 * Defaults to the empty string.
	 */
	protected String getBEGINToken(EObject semanticObject, RuleCall ruleCall, INode node) { return ""; }
	
	/**
	 * Synthetic terminal rule. The concrete syntax is to be specified by clients.
	 * Defaults to the empty string.
	 */
	protected String getENDToken(EObject semanticObject, RuleCall ruleCall, INode node) { return ""; }
	
	/**
	 * terminal NEWLINE:
	 *     '\r'? '\n';
	 */
	protected String getNEWLINEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\n";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Pipeline_NEWLINETerminalRuleCall_2_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_2_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_3_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_3_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_4_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_4_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_5_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_5_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_6_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_6_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_7_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_7_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_8_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_8_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_NEWLINETerminalRuleCall_9_1_q.equals(syntax))
				emit_Pipeline_NEWLINETerminalRuleCall_9_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PreserveStashes___BEGINTerminalRuleCall_2_0_ENDTerminalRuleCall_2_2__q.equals(syntax))
				emit_PreserveStashes___BEGINTerminalRuleCall_2_0_ENDTerminalRuleCall_2_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     agents+=Agent (ambiguity) environments+=Environment
	 *     agents+=Agent (ambiguity) options+=Option
	 *     agents+=Agent (ambiguity) parameter_directives+=Parameter_Directive
	 *     agents+=Agent (ambiguity) stages+=Stage
	 *     agents+=Agent (ambiguity) tools+=Tool
	 *     agents+=Agent (ambiguity) triggers+=Trigger
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_2_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     options+=Option (ambiguity) environments+=Environment
	 *     options+=Option (ambiguity) parameter_directives+=Parameter_Directive
	 *     options+=Option (ambiguity) stages+=Stage
	 *     options+=Option (ambiguity) tools+=Tool
	 *     options+=Option (ambiguity) triggers+=Trigger
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_3_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     triggers+=Trigger (ambiguity) environments+=Environment
	 *     triggers+=Trigger (ambiguity) parameter_directives+=Parameter_Directive
	 *     triggers+=Trigger (ambiguity) stages+=Stage
	 *     triggers+=Trigger (ambiguity) tools+=Tool
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_4_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     parameter_directives+=Parameter_Directive (ambiguity) environments+=Environment
	 *     parameter_directives+=Parameter_Directive (ambiguity) stages+=Stage
	 *     parameter_directives+=Parameter_Directive (ambiguity) tools+=Tool
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_5_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     environments+=Environment (ambiguity) stages+=Stage
	 *     environments+=Environment (ambiguity) tools+=Tool
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_6_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     tools+=Tool (ambiguity) stages+=Stage
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_7_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     stages+=Stage (ambiguity) (rule end)
	 *     stages+=Stage (ambiguity) post+=Post
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_8_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     NEWLINE?
	 *
	 * This ambiguous syntax occurs at:
	 *     post+=Post (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Pipeline_NEWLINETerminalRuleCall_9_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (BEGIN END)?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'PreserveStashes' (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_PreserveStashes___BEGINTerminalRuleCall_2_0_ENDTerminalRuleCall_2_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
