<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="travisCI_metamodel" nsURI="http://www.example.org/travisCI_metamodel"
    nsPrefix="travisCI_metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="On">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch_type" eType="#//BRANCH_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rubygems" eSuperTypes="#//Deploy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BRANCH_TYPE">
    <eLiterals name="SAFELIST"/>
    <eLiterals name="BLOCKLIST" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitHub" eSuperTypes="#//Deploy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heroku" eSuperTypes="#//Deploy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="app" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="install" upperBound="-1"
        eType="#//Install" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" upperBound="-1" eType="#//Job"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//Language"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline_environment" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//If" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch" upperBound="-1"
        eType="#//Branch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" upperBound="-1"
        eType="#//Stage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allow_failure" eType="#//Allow_Failure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="env_type" eType="#//ENV_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allow_Failure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//If" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" upperBound="-1"
        eType="#//Environment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Install">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fast_finish" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage_type" eType="#//STAGE_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
        eType="#//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploy" upperBound="-1"
        eType="#//Deploy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//If" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job_type" eType="#//JOB_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//Language"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" upperBound="-1"
        eType="#//Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Npm" eSuperTypes="#//Deploy"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ENV_TYPE">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="JOBS" value="1"/>
    <eLiterals name="GLOBAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="STAGE_TYPE">
    <eLiterals name="NONE"/>
    <eLiterals name="DEPLOY" value="1"/>
    <eLiterals name="COMPILE" value="2"/>
    <eLiterals name="TEST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JOB_TYPE">
    <eLiterals name="INCLUDE" value="1"/>
    <eLiterals name="EXCLUDE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool_Framework">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deploy" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api_key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skip_cleanup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" upperBound="-1" eType="#//On"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" upperBound="-1"
        eType="#//Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//If" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tool_framework" eType="#//Tool_Framework"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
