/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.cicd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CICDStandaloneSetup extends CICDStandaloneSetupGenerated {

	public static void doSetup() {
		new CICDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
