/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.gha;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GHAStandaloneSetup extends GHAStandaloneSetupGenerated {

	public static void doSetup() {
		new GHAStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
