<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="circleCI_metamodel" nsURI="http://www.example.org/circleCI_metamodel"
    nsPrefix="circleCI_metamodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="#//WHEN_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="working_directory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="."/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environments" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_output_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10m"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shell" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="run_commands" lowerBound="1"
        upperBound="-1" eType="#//RunCommand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Docker_Auth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestoreCache" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keys" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Docker_Aws_Auths">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aws_access_key_id" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aws_secret_access_key"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateJobName hasOneExecutorType ExecutorExistsInJobs"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateJobName" value="Tuple {&#xA;&#x9;message : String = 'Duplicate Job Name. Choose a different job name to ensure uniqueness within the pipeline.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().jobs->forAll(j | j &lt;> self implies j.name &lt;> self.name)&#xA;}.status"/>
      <details key="hasOneExecutorType" value="Tuple {&#xA;&#x9;message : String = 'Each job should only specify one executor type. Please ensure that each job has a unique executor type assigned.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;&#x9;self.executors->collect(e | e.oclType())->asSet()->size() &lt;= 1&#xA;}.status"/>
      <details key="ExecutorExistsInJobs" value="Tuple {&#xA;&#x9;message : String = 'Ensure that the executor name matches one of the defined executors in the Pipeline\'s configuration',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;    &#x9;(self.reuseExecutor &lt;> null and self.reuseExecutor->notEmpty()) implies&#xA;&#x9;&#x9;        &#x9;&#x9;Pipeline.allInstances().executors->exists(ex | ex.name = self.reuseExecutor)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environments" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reuseExecutor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executors" upperBound="-1"
        eType="#//Executor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//Executor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docker_layer_caching" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceClass" lowerBound="1"
        eType="#//MACHINE_RESOURCE_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PARAMETER_TYPES">
    <eLiterals name="STRING" literal="string"/>
    <eLiterals name="BOOLEAN" value="1" literal="boolean"/>
    <eLiterals name="INTEGER" value="2" literal="integer"/>
    <eLiterals name="ENUM" value="3" literal="enum"/>
    <eLiterals name="EXECUTOR" value="4" literal="executor"/>
    <eLiterals name="STEPS" value="5" literal="steps"/>
    <eLiterals name="ENVIRONMENT_VARIABLE_NAME" value="6" literal="environment_variable_name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BRANCH_TYPE">
    <eLiterals name="only"/>
    <eLiterals name="ignore" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersistToWorkspace" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paths" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoreArtifact" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoreTestResults" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetupRemoteDocker" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docker_layer_caching" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="EnumValuesNotEmpty EnumValuesEmptyForNonEnum CheckValidBooleanDefaultValue validParameterTypes nonDuplicateParameterName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="EnumValuesNotEmpty" value="Tuple {&#xA;&#x9;message : String = 'Enum parameter must have non-empty enum values',&#xA;&#x9;status : Boolean = &#xA;    &#x9;&#x9;self.type = PARAMETER_TYPES::ENUM implies&#xA;        &#x9;&#x9;not self.enumValues->isEmpty() and self.enumValues->notEmpty()&#xA;}.status"/>
      <details key="EnumValuesEmptyForNonEnum" value="Tuple {&#xA;&#x9;message : String = 'Non-enum parameter must not have enum values. Remove enumValues entry',&#xA;&#x9;status : Boolean = &#xA;    &#x9;&#x9;self.type &lt;> PARAMETER_TYPES::ENUM implies&#xA;        &#x9;&#x9;self.enumValues->isEmpty() and self.enumValues->isEmpty()&#xA;}.status"/>
      <details key="CheckValidBooleanDefaultValue" value="Tuple {&#xA;&#x9;message : String = 'Boolean parameter must have default value as &quot;true&quot; or &quot;false&quot;',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;    self.type = PARAMETER_TYPES::BOOLEAN implies&#xA;&#x9;&#x9;        (self.default = 'true' or self.default = 'false')&#xA;}.status"/>
      <details key="validParameterTypes" value="Tuple {&#xA;&#x9;message : String = 'Invalid parameter type. Pipeline parameters can only have types: string, boolean, integer, or enum.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;        self.type = PARAMETER_TYPES::STRING or&#xA;&#x9;&#x9;        self.type = PARAMETER_TYPES::BOOLEAN or&#xA;&#x9;&#x9;        self.type = PARAMETER_TYPES::INTEGER or&#xA;&#x9;&#x9;        self.type = PARAMETER_TYPES::ENUM&#xA;}.status"/>
      <details key="nonDuplicateParameterName" value="Tuple {&#xA;&#x9;message : String = 'Duplicate Parameter Name. Choose a different Parameter name to ensure uniqueness within the pipeline.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().jobs.parameters->union(Pipeline.allInstances().commands.parameters)->forAll(p | p &lt;> self implies p.name &lt;> self.name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PARAMETER_TYPES"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumValues" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacOs" eSuperTypes="#//Executor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xcode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceClass" lowerBound="1"
        eType="#//MACOS_RESOURCE_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when_unless" eType="#//When_Unless"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobworkflow" lowerBound="1"
        upperBound="-1" eType="#//JobWorkflow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WHEN_TYPE">
    <eLiterals name="on_success"/>
    <eLiterals name="always" value="1"/>
    <eLiterals name="on_fail"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Docker" eSuperTypes="#//Executor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="docker_auth" eType="#//Docker_Auth"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="docker_aws_auth" eType="#//Docker_Aws_Auths"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entrypoint" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceClass" lowerBound="1"
        eType="#//DOCKER_RESOURCE_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSSHKeys" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fingerprints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SaveCache" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paths" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="#//WHEN_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachWorkspace" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="at" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="When_Unless" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="when_step" lowerBound="1"
        upperBound="-1" eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unless_step" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" lowerBound="1"
        eType="#//BRANCH_TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validCronSyntax"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="validCronSyntax" value="Tuple {&#xA;&#x9;message : String = 'Not a valid Cron syntax. Ensure that the pattern follows the format: [minute] [hour] [day of month] [month] [day of week], where each field is separated by a space.',&#xA;&#x9;status : Boolean = &#xA;    &#x9;&#x9;self.cron.matches('(?:[0-9]|1[0-9]|2[0-3]|H|L|\\*|\\?|[0-5]?[0-9]|\\*/[0-9]+) (?:[0-9]|1[0-9]|2[0-3]|\\*|L|\\?|[01]?[0-9]|2[0-9]|3[01]|W|L\\-?[0-6]|#[1-5]|\\*/[0-9]+) (?:[0-9]|1[0-9]|2[0-3]|\\*|L|\\?|[01]?[0-9]|2[0-9]|3[01]|W|L\\-?[0-6]|#[1-5]) (?:[0-9]|1[0-2]|\\*|L|\\?|\\*/[0-9]+) (?:[0-7]|\\*|L|\\?|#[1-5])')&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cron" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checkout" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executor" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateExecutorName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateExecutorName" value="Tuple {&#xA;&#x9;message : String = 'Duplicate Executor Name. Choose a different Executor name to ensure uniqueness within the pipeline.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().jobs.executors->union(Pipeline.allInstances().executors)->forAll(p | p &lt;> self implies p.name &lt;> self.name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shell" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="working_directory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environments" upperBound="-1"
        eType="#//Environment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orbs" upperBound="-1" eType="#//Orb"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflow" eType="#//Workflow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" lowerBound="1" upperBound="-1"
        eType="#//Job" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executors" lowerBound="1"
        upperBound="-1" eType="#//Executor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Orb">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateCommandName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateCommandName" value="Tuple {&#xA;&#x9;message : String = 'Duplicate Command Name. Choose a different Command name to ensure uniqueness within the pipeline.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().commands->forAll(p | p &lt;> self implies p.name &lt;> self.name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrix_exclude" upperBound="-1"
        eType="#//MatrixParams" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrix_params" lowerBound="1"
        upperBound="-1" eType="#//MatrixParams" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobWorkflow">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredJobExists WorkflowJobExists nonDuplicateJobWorkflowName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="requiredJobExists" value="Tuple {&#xA;&#x9;message : String = 'Required Job does not exist. Select an existing pipeline Job',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;self.requires->notEmpty() implies self.requires->forAll(rj | Job.allInstances()->exists(j | j.name = rj))&#xA;}.status"/>
      <details key="WorkflowJobExists" value="Tuple {&#xA;&#x9;message : String = 'Ensure that jobs referenced in the workflow exist in Job\'s configuration',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().jobs->exists(job | job.name = self.name)&#xA;}.status"/>
      <details key="nonDuplicateJobWorkflowName" value="Tuple {&#xA;&#x9;message : String = 'Duplicate JobWorkflow Name. Choose a different jobWorkflow name to ensure uniqueness within the pipeline.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;Pipeline.allInstances().workflow.jobworkflow->forAll(jw | jw &lt;> self implies jw.name &lt;> self.name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requires" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approvalJob" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrix" eType="#//Matrix"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DOCKER_RESOURCE_TYPE">
    <eLiterals name="SMALL" literal="small"/>
    <eLiterals name="MEDIUM" value="1" literal="medium"/>
    <eLiterals name="MEDIUM_PLUS" value="2" literal="medium_plus"/>
    <eLiterals name="LARGE" value="3" literal="large"/>
    <eLiterals name="XLARGE" value="4" literal="xlarge"/>
    <eLiterals name="TWO_XLARGE" value="5" literal="two_xlarge"/>
    <eLiterals name="TWO_XLARGE_PLUS" value="6" literal="two_xlarge_plus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MACOS_RESOURCE_TYPE">
    <eLiterals name="MACOS_X86_MEDIUM_GEN2" literal="macos.x86.medium.gen2"/>
    <eLiterals name="MACOS_M1_MEDIUM_GEN" value="1" literal="macos.m1.medium.gen1"/>
    <eLiterals name="MACOS_M1_LARGE_GEN1" value="2" literal="macos.m1.large.gen1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MACHINE_RESOURCE_TYPE">
    <eLiterals name="MEDIUM" literal="medium"/>
    <eLiterals name="LARGE" value="1" literal="large"/>
    <eLiterals name="XLARGE" value="2" literal="xlarge"/>
    <eLiterals name="TWO_XLARGE" value="3" literal="two_xlarge"/>
    <eLiterals name="TWO_XLARGE_PLUS" value="4" literal="two_xlarge_plus"/>
  </eClassifiers>
</ecore:EPackage>
