/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.cicd.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CICDProposalProvider extends AbstractCICDProposalProvider {
}
