version: "1.0"

steps:
  clone:
    title: Cloning repository
    image: ${{docker_image}}
    
    commands:
      - npm install gulp
      - npm install
    
    
    
  build:
    title: Building Docker image
    
    commands:
    
    environment:
      - 'ENV=${{SECRET}}'
    
      when:
        condition:
          any:
      	  "branch = 1"
    

trigger:
  event:
  - master

